apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config-map
  namespace: bankapp
data:
  MYSQL_DATABASE: bankappdb
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  MYSQL_USER: root
  OLLAMA_URL: http://ollama-service:11434