apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv 
  labels:
    app: mysql

spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql

      ---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ollama-pv 
  labels:
    app: ollama

spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/ollama