kind: Secret
apiVersion: v1
metadata:
  name: bankapp-secrets
  namespace: bankapp
type: Opaque

data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # base64 encode for "root"
  MYSQL_PASSWORD: cm9vdA== # base64 encode for "root"